### ISSUE TITLE
Error occurred while enabling TropiqueBlockDrops v1.2.1

### ISSUE THREAD

**Issue by ErythroCraft** [BlueDolphinCow/Tropique-Block-Drops-Plugin#2]
HI,

I installed your plugin on my server.
So, the server console say this bug.

Please fix this fast.
THX

[19:20:11] [Server thread/INFO]: [TropiqueBlockDrops] Enabling TropiqueBlockDrops v1.2.1
[19:20:11] [Server thread/ERROR]: Error occurred while enabling TropiqueBlockDrops v1.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at me.sevenwone.tropiqueblockdrops.TropiqueBlockDrops.onEnable(TropiqueBlockDrops.java:18) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 11 more
[19:20:11] [Server thread/INFO]: [WolfyUtilities] Enabling WolfyUtilities v1.6.3.11

**Comment by ErythroCraft** [comment]
Sorry, my misstake.

I was not installing WorldGuard.
